### PR TITLE
Repair broken reference

### LINKED ISSUE #278: Map option reference broken gmaps
When you use torque with GMaps, it doesn't work, because the gmap instance reference is missing.

It is related with this [issue](https://github.com/CartoDB/cartodb.js/issues/1528).

### PR DESCRIPTION
**Pull request by donflopez**
Fix #278 and [#1528](https://github.com/CartoDB/cartodb.js/issues/1528)

### CODE REVIEW

**Comment by alonsogarciapablo** [comment]
In theory, Torque layers should work as standalone layers (eg: someone should be able to add a Torque layer to an existing Google Maps map, as in [this example](https://github.com/CartoDB/torque/blob/16bac52b91bd7b57e020c90a8bffc17e86a2db7b/examples/navy_gmaps.html#L78)). [OverlayView](https://developers.google.com/maps/documentation/javascript/3.exp/reference#OverlayView) implements a `setMap` method, but I'm not sure that'll set `this.map` (it's being used [in that example too](https://github.com/CartoDB/torque/blob/16bac52b91bd7b57e020c90a8bffc17e86a2db7b/examples/navy_gmaps.html#L85)). What do you think @donflopez?

Also, I traveled back in time to find out the bug we're seeing in CartoDB.js was introduced in https://github.com/CartoDB/cartodb.js/commit/77449e90e7e7e4667a38755cee6affdbae30b3ea, where we [removed the map option we're passing as an option](https://github.com/CartoDB/cartodb.js/commit/77449e90e7e7e4667a38755cee6affdbae30b3ea#diff-51d0416fc72caf327c2f5d72b19f2bacL35).

**Comment by donflopez** [comment]
Yep, that's the problem with the inheritance and mutability; you don't know where or who is changing the state of your class, here is pretty hard to find out where is this.map or this.options.maps.

CanvasLayer prototype is inheriting from OverlayView instance from GMaps library, so we don't know what is happening exactly and the code is obfuscated.

Here, in the examples we pass the map instance as an option; but later we set the map using a GMaps method that seems to be the real handler for the map instance because the map passed as an options have a blind end, it isn't used.

So I've removed it to avoid confusions, and I think that this.map is the correct way because GMaps library set it and it's available when we use it on torque.js. It is too confusing, so maybe I'm missing something.

What do you think @alonsogarciapablo?

**Comment by alonsogarciapablo** [comment]
> Here, in the examples we pass the map instance as an option; but later we set the map using a GMaps method that seems to be the real handler for the map instance because the map passed as an options have a blind end, it isn't used.

I'm ok with it as long as:
1. `setMap` is actually setting `this.map`.
2. CanvasLayer doens't actually need the `map` option you removed.

I guess we can remove the `map` option from [this example](https://github.com/CartoDB/torque/blob/16bac52b91bd7b57e020c90a8bffc17e86a2db7b/examples/navy_gmaps.html#L78) and see if it works... 👍 ?

**Comment by donflopez** [comment]
Yeah! I tried it, and it works. I've committed the change.

Is there any other example using GMaps with torque?

**Comment by alonsogarciapablo** [comment]
Not sure if there're more examples. I'm not very familiar with this repo.

:+1: Thanks! 👏

**Comment by donflopez** [comment]
I checked, there are two more, but the examples are broken :( If you want I can change the map as an option, but they don't work for other reasons.

Thanks to you!

**Pull request merged**
