### PR TITLE
Add getOpacity/setOpacity to canvaslayer

### PR DESCRIPTION
**Pull request by knownasilya**
Align with the MapType API

### CODE REVIEW

**Comment by javisantana** [comment]
leaflet layer should behave in the same way, probably it already does it cc @fdansv

**Comment by fdansv** [comment]
I'm not sure why would the layer need an abstraction like this, since it's super simple to change the opacity using the canvas field. Maybe I'm missing something, but a use case or a rationale for this would be helpful.

**Comment by fdansv** [comment]
OK, I see it. Leaflet.CanvasLayer does have set/getOpacity, so ok to this.
:shipit:

**Comment by knownasilya** [comment]
Sweet! Thanks.

**Pull request merged**
