### PR TITLE
New docs folder for developer center

### PR DESCRIPTION
**Pull request by csubira**
The new documentation folder (`docs`) is created to meet the requirements of the new developer center.

At the moment, `docs` folder contains four folders or categories (`guides`, `reference`, `examples` and `support`). To start, each of them is filled with older information (usually contained in `doc` folder).

In this first step, using this branch, the new workflow of documentation repository (for importing and displaying content) is going to be tested. 

Once validated, the second step is to get your validation @ivanmalagon about content (correcting current information or adding new items)

### CODE REVIEW

**Comment by csubira** [comment]
This PR has been updated to remove old documentation (used in carto.com/docs, now deprecated and redirected to Developer Center)
The outcome of this changes is already in [production](https://carto.com/developers/torque-js/), as this branch was the one connected to Developer Center, the only change would me merging this folder to master so it can be updated when developing.

**Comment by VictorVelarde** [comment]
Hi @csubira I have some doubts regarding to the **examples**

There are currently 2 folders: `/examples` and `/docs/examples`. The one that's currently being used at dev-center is the first one, and I guess that the second one will be the new one. But right now, they are not equal. There are more examples in the 'old one' and some, like 'car', just appear in the second (which only has 4). I guess we should review and merge both sets

**Comment by csubira** [comment]
Yes! You are right @VictorVelarde , so here there are the last changes I made:
- Moved `examples` folder from source to `docs` folder
- Remove `misc` folder since the `*.md` files included are already duplicated in guides.
- Replace _vendor/leaflet_ imports in examples since it was donde before to examples that were updated to be published -> then delete `vendor` folder.
- [Changed in developers repository the new origin of examples](https://github.com/CartoDB/developers/commit/679a0ff483d4b9378ac2520e5fa8d559cf787434)
-  Check that the examples show properly in production https://carto.com/developers/torque-js/examples/

**Comment by VictorVelarde** [comment]
Nice work @csubira 👍 
I just made a little change to examples 'categories' but IMO it's ready to be merged

**Pull request merged**
