### PR TITLE
Allow to render several keys/steps with a given range

### LINKED ISSUE #246: render several keys/steps
**Value**: Having a method to freeze the visualisation and display all the available data is useful when you want to compare against other static representations of the data.

TODO
 - [x] Support for rendering several keys/steps at low level
 - [x] Expose a new public method to render a range: start step, end step.

cc @viddo

### PR DESCRIPTION
**Pull request by rochoa**
- At low level point renderer now allows to receive several keys
 in renderTile.
- leaflet and gmaps layers expose renderRange(start, end) to be able
 to set and render a range of steps.

This closes #246

### CODE REVIEW

**Comment by rochoa** [comment]
cc @javisantana @viddo

**Comment by viddo** [comment]
code-wise LGTM, although I'm not too familiar with this `key` prop and what side-effects this kind of change might have

**Comment by rochoa** [comment]
We could add a property like:

```js
Object.defineProperty(this, 'key', {
  writable: false,
  get: function() {
    return self.keys[0];
  }
});
```

What do you think?

**Comment by viddo** [comment]
:+1:

**Comment by rochoa** [comment]
I added the `key` property we talked about.

**Pull request merged**
