### PR TITLE
Fix #263 Implementation of torque layer for OpenLayers for 3.17 or later.

### LINKED ISSUE #263: Contribution of ol3 Torque Layer's implementation to CartoDb
Contribution of Torque Layer's implementation for OpenLayers version 3.17 and above to CartoDb by Bloomberg.

### PR DESCRIPTION
**Pull request by ashchurova**

### CODE REVIEW

**Comment by ashchurova** [comment]
@javisantana removed generated files from previous pull request.

**Comment by dprophet** [comment]
@mbforr @javisantana Any reason this pull requests isnt completed?

**Comment by javisantana** [comment]
@donflopez could you please review and test this PR?

**Comment by ashchurova** [comment]
@donflopez Thanks!!!

**Pull request merged**
