### PR TITLE
Allows for zero marker-fill-opacity

### LINKED ISSUE #155: marker-fill-opacity does not work
using this style in a table with a single point:

```
#untitled_table_5{
  marker-fill-opacity: 0.0;
  marker-line-color: #000000;
  marker-line-width: 1.5;
  marker-line-opacity: 1;
  marker-type: ellipse;
  marker-width: 6;
  marker-fill: #FFFFFF;
}
```

should not fill the points but it does

### PR DESCRIPTION
**Pull request by fdansv**
Fixes #155. Super simple fix.
@javisantana

### CODE REVIEW

**Comment by javisantana** [comment]
sounds good:

- why don't apply the same optimization we have for lines? (when the alpha is = just not fill)
- what should happen when marker-fill-opacity and marker-opacity are both enabled, should we multiply them?

**Comment by javisantana** [comment]
also NEWS

**Comment by fdansv** [comment]
@javisantana 

I feel like multiplying ```marker-fill-opacity``` and ```marker-opacity``` is overengineering it a bit. Plus, at the moment we're only using marker-opacity if there's isn't a ```marker-fill-opacity``` property assigned. I think  ```marker-opacity``` should set the opacity for both stroke and/or fill, if any isn't specified ```marker-fill-opacity``` / ```marker-line-opacity```.

**Comment by fdansv** [comment]
In which case we just have to erase [this line](https://github.com/CartoDB/torque/blob/fill-opacity/lib/torque/renderer/cartocss_render.js#L57)

**Comment by javisantana** [comment]
> I feel like multiplying marker-fill-opacity and marker-opacity is overengineering it a bit.

haha, what does mapnik by default?

and what about the optimization?

**Pull request merged**
