### PR TITLE
Add small script to export torque tiles from CartoDB and PostGIS

### PR DESCRIPTION
**Pull request by andrewxhill**

### CODE REVIEW

**Comment by javisantana** [comment]
Things I see

- move to tools folder
- add a readme
- the torque query is not the best one I think, see https://github.com/CartoDB/torque/blob/sql/sql/torque_query.py#L3
- abstract the fetch data thing, there are a lot of repeated code
- I'd try to follow pep8

**Comment by andrewxhill** [comment]
funny about the sql query, i pulled that from master. where can i find the latest and greatest?

**Comment by ohasselblad** [comment]
i think it'd be this query: https://github.com/CartoDB/Windshaft/blob/master/lib/windshaft/renderers/torque/renderer.js#L102-L135

**Comment by javisantana** [comment]
@ohasselblad yes, that's valid but it's more complicated (it takes buffers into account) but up to you

**Comment by andrewxhill** [comment]
I think the only thing missing is some test coverage

**Comment by andrewxhill** [comment]
bump

**Comment by fdansv** [comment]
Hey guys, @rochoa and I spent some time yesterday working on the tool. I think, though, that it should have its own repo instead of being in a utils directory.

**Comment by javisantana** [comment]
agree, but lets have it working, then we will move to a different repo and will create the pip thing

**Comment by fdansv** [comment]
Since both the CartoDB and Postgres sources are working correctly with the provider, and we've added tilejson export with the tiles, I'm moving this to [its own repo](https://github.com/CartoDB/torque-gen) as discussed.

**Pull request closed without merging**
